/* AUTOMATICALLY GENERATED CODE DO NOT MODIFY */
/*   To generate run: "serverpod generate"    */

// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: public_member_api_docs
// ignore_for_file: type_literal_in_constant_pattern
// ignore_for_file: use_super_parameters
// ignore_for_file: invalid_use_of_internal_member

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'package:serverpod_client/serverpod_client.dart' as _i1;
import '../users/messenger_user.dart' as _i2;
import '../devices/device_platform.dart' as _i3;
import 'package:messenger_client/src/protocol/protocol.dart' as _i4;

/// A client installation for a [MessengerUser], not an authentication session.
///
/// Used later to choose push-notification targets. [pushToken] stays unused
/// until the notification phase.
abstract class Device implements _i1.SerializableModel {
  Device._({
    this.id,
    required this.userId,
    this.user,
    required this.clientId,
    required this.platform,
    this.pushToken,
    DateTime? createdAt,
    required this.lastSeenAt,
  }) : createdAt = createdAt ?? DateTime.now();

  factory Device({
    int? id,
    required int userId,
    _i2.MessengerUser? user,
    required _i1.UuidValue clientId,
    required _i3.DevicePlatform platform,
    String? pushToken,
    DateTime? createdAt,
    required DateTime lastSeenAt,
  }) = _DeviceImpl;

  factory Device.fromJson(Map<String, dynamic> jsonSerialization) {
    return Device(
      id: jsonSerialization['id'] as int?,
      userId: jsonSerialization['userId'] as int,
      user: jsonSerialization['user'] == null
          ? null
          : _i4.Protocol().deserialize<_i2.MessengerUser>(
              jsonSerialization['user'],
            ),
      clientId: _i1.UuidValueJsonExtension.fromJson(
        jsonSerialization['clientId'],
      ),
      platform: _i3.DevicePlatform.fromJson(
        (jsonSerialization['platform'] as String),
      ),
      pushToken: jsonSerialization['pushToken'] as String?,
      createdAt: jsonSerialization['createdAt'] == null
          ? null
          : _i1.DateTimeJsonExtension.fromJson(jsonSerialization['createdAt']),
      lastSeenAt: _i1.DateTimeJsonExtension.fromJson(
        jsonSerialization['lastSeenAt'],
      ),
    );
  }

  /// The database id, set if the object has been inserted into the
  /// database or if it has been fetched from the database. Otherwise,
  /// the id will be null.
  int? id;

  int userId;

  /// The [MessengerUser] this installation belongs to.
  _i2.MessengerUser? user;

  /// Stable id generated by the client for this installation.
  _i1.UuidValue clientId;

  /// Platform this installation is running on.
  _i3.DevicePlatform platform;

  /// Push token. Null until notifications are implemented.
  String? pushToken;

  DateTime createdAt;

  DateTime lastSeenAt;

  /// Returns a shallow copy of this [Device]
  /// with some or all fields replaced by the given arguments.
  @_i1.useResult
  Device copyWith({
    int? id,
    int? userId,
    _i2.MessengerUser? user,
    _i1.UuidValue? clientId,
    _i3.DevicePlatform? platform,
    String? pushToken,
    DateTime? createdAt,
    DateTime? lastSeenAt,
  });
  @override
  Map<String, dynamic> toJson() {
    return {
      '__className__': 'Device',
      if (id != null) 'id': id,
      'userId': userId,
      if (user != null) 'user': user?.toJson(),
      'clientId': clientId.toJson(),
      'platform': platform.toJson(),
      if (pushToken != null) 'pushToken': pushToken,
      'createdAt': createdAt.toJson(),
      'lastSeenAt': lastSeenAt.toJson(),
    };
  }

  @override
  String toString() {
    return _i1.SerializationManager.encode(this);
  }
}

class _Undefined {}

class _DeviceImpl extends Device {
  _DeviceImpl({
    int? id,
    required int userId,
    _i2.MessengerUser? user,
    required _i1.UuidValue clientId,
    required _i3.DevicePlatform platform,
    String? pushToken,
    DateTime? createdAt,
    required DateTime lastSeenAt,
  }) : super._(
         id: id,
         userId: userId,
         user: user,
         clientId: clientId,
         platform: platform,
         pushToken: pushToken,
         createdAt: createdAt,
         lastSeenAt: lastSeenAt,
       );

  /// Returns a shallow copy of this [Device]
  /// with some or all fields replaced by the given arguments.
  @_i1.useResult
  @override
  Device copyWith({
    Object? id = _Undefined,
    int? userId,
    Object? user = _Undefined,
    _i1.UuidValue? clientId,
    _i3.DevicePlatform? platform,
    Object? pushToken = _Undefined,
    DateTime? createdAt,
    DateTime? lastSeenAt,
  }) {
    return Device(
      id: id is int? ? id : this.id,
      userId: userId ?? this.userId,
      user: user is _i2.MessengerUser? ? user : this.user?.copyWith(),
      clientId: clientId ?? this.clientId,
      platform: platform ?? this.platform,
      pushToken: pushToken is String? ? pushToken : this.pushToken,
      createdAt: createdAt ?? this.createdAt,
      lastSeenAt: lastSeenAt ?? this.lastSeenAt,
    );
  }
}
